//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは xsd によって自動生成されました。Version=4.8.3928.0 です。
// 
namespace HHFO.Config {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ErrorMessage {
        
        private string unAuthrizeCreateFileField;
        
        private string unAuthrizeCreateDirField;
        
        private string unExpectedExceptionCreateDirField;
        
        private string unExpectedExceptionCreateXmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnAuthrizeCreateFile {
            get {
                return this.unAuthrizeCreateFileField;
            }
            set {
                this.unAuthrizeCreateFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnAuthrizeCreateDir {
            get {
                return this.unAuthrizeCreateDirField;
            }
            set {
                this.unAuthrizeCreateDirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnExpectedExceptionCreateDir {
            get {
                return this.unExpectedExceptionCreateDirField;
            }
            set {
                this.unExpectedExceptionCreateDirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnExpectedExceptionCreateXml {
            get {
                return this.unExpectedExceptionCreateXmlField;
            }
            set {
                this.unExpectedExceptionCreateXmlField = value;
            }
        }
    }
}
